/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_canbus_api_Canbus */

#ifndef _Included_com_android_canbus_api_Canbus
#define _Included_com_android_canbus_api_Canbus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_canbus_api_Canbus
 * Method:    open
 * Signature: ()Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_android_1canbus_1api_Canbus_open
  (JNIEnv *, jclass);

/*
 * Class:     com_android_canbus_api_Canbus
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_1canbus_1api_Canbus_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
